---
title: "Case Study 08"
author: Yixuan Zhao
date: 10-25-2022
output:
  html_document: default
  github_document: default
  powerpoint_presentation: default
  word_document: default
---


```{r,echo = FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
url = "https://gml.noaa.gov/webdata/ccgg/trends/ch4/ch4_annmean_gl.txt"
df = read.table(url, col.names = c("year", "mean", "unc"))
# rmarkdown::render("Y:/GitHubTB/case_studies-yzhao72/week_08/case_study_08.Rmd", output_format = "all")
```


```{r}
min_year = df$year %>% min()
max_year = df$year %>% max()
df %>% 
  mutate(sd = sd(mean)) %>% 
  as_tibble() %>% 
  ggplot(., aes(x = year, y = mean)) +
  geom_line(color = "black", lwd = 1) +
  geom_point(size = 2, color = "red") +
  scale_x_continuous(breaks = seq(min_year, max_year, 5)) +
  theme_bw() +
  labs(x = "Year", y = "Mean", 
       title= "Trends in Atmospheric Chemical Compound")
```


```{r}
summ = df %>% 
  slice(-1) %>% 
  mutate(Years = case_when(
    year %in% seq(1960, 1969) ~ "1960 - 1969", 
    year %in% seq(1970, 1979) ~ "1970 - 1979", 
    year %in% seq(1980, 1989) ~ "1980 - 1989", 
    year %in% seq(1990, 1999) ~ "1990 - 1999", 
    year %in% seq(2000, 2009) ~ "2000 - 2009", 
    year %in% seq(2010, 2019) ~ "2010 - 2019", 
    year %in% seq(2020, 2029) ~ "2020 -  "
  )) %>% 
  group_by(Years) %>% 
  dplyr::summarise(Mean = mean(mean), 
                   S.D. = sd(mean), 
                   Min = min(mean), 
                   Max = max(mean))
knitr::kable(summ,'simple')
```